name: Publish Devcontainer Image

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/build-devcontainer.yml" # this file

permissions:
  packages: write
  contents: read

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: 💻 Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host arm-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      # Creating our own builder lets us have more control over the build process
      # we are making the actions runner natively build the amd image, but SSH into our arm VM for the arm image
      # https://www.docker.com/blog/speed-up-building-with-docker-buildx-and-graviton2-ec2/
      # this allows u to still use build-push-action, but docker will automatically choose which builder to use based on the platform
      - name: Setup Buildx Instances
        shell: bash
        run: |
          docker buildx create --use --name main-builder --platform=linux/amd64 --driver=docker-container
          docker buildx create --append --name=main-builder --platform=linux/arm64 ssh://arm-vm
          docker buildx inspect main-builder --bootstrap
          docker buildx ls

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # I don't need to keep track of previous versions, so I just use latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max